name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login_and_deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Dev
      url: https://github.com
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run:  |-
          docker build . --file Dockerfile --tag jaganthoutam/docker-freeswitch:latest
          docker push jaganthoutam/docker-freeswitch:latest
        
      
      
